### PR TITLE
Add ContentImage Component

### PR DESCRIPTION
**Pull request by mirceacr**
https://github.com/spartansystems/component-booster/issues/12

Why:

* We need a component that will render an `IMG` element with optional,
  but recommended, `ALT` and `TITLE` attribute values.

This change addresses the need by:

* Add component with no default props.
* Add storybook for the component, with custom props.
* Add basic styling for the component.
* Add tests for different cases of use for the component.

### CODE REVIEW

**Review by andandandandrew — APPROVED** [review]
👍

**Review by bbrock25 — COMMENTED** [review]
if we are only wrapping an img, is this component actually necessary @andandandandrew ?

**Comment by mirceacr** [comment]
@andandandandrew please see the above question, so we can merge it or drop it after you answer. thanks!

**Comment by dfish9** [comment]
this looks like an abandoned branch, closing

**Pull request closed without merging**
